
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learnandtest?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: oauth-center
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: oauth-center

security:
  oauth2:
    resource:
      id: oauth-center
      user-info-uri: http://localhost:8080/user/me
      prefer-token-info: false


#logging:
#  level:
#    root: debug

