server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSIONCOUPON

security:
  oauth2:
    client:
      client-id: GSForOCS2
      client-secret: 12345
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me

logging:
  level:
    root: debug
spring:
  thymeleaf:
    cache: false

  cloud:
    consul:
      discovery:
        service-name: oauth-client-sso2
        instance-id: ${spring.application.name}:${random.value}
  application:
    name: oauth-client-sso2


feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true
