spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
    timeout: 0
    password:
  application:
    name: seckill-server

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: seckill-server

security:
  oauth2:
    resource:
      id: seckill-server
      user-info-uri: http://localhost:8080/user
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG

server:
  port: 8090
